"""empty message

Revision ID: 24cd1b508632
Revises: f3805b4aee56
Create Date: 2022-03-24 20:33:50.730533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24cd1b508632'
down_revision = 'f3805b4aee56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('looking', sa.Boolean(), nullable=True))
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    
    op.execute('UPDATE artist SET name=' + "''" + ' WHERE name IS NULL;')
    op.execute('UPDATE artist SET city=' + "''" + ' WHERE city IS NULL;')
    op.execute('UPDATE artist SET state=' + "''" + ' WHERE state IS NULL;')

    op.alter_column('artist', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('artist', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('artist', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    op.add_column('venue', sa.Column('looking', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('genres', sa.String(length=120), nullable=True))

    op.execute('UPDATE venue SET name = ' + "''" + ' WHERE name IS NULL;')
    op.execute('UPDATE venue SET city = ' + "''" + ' WHERE city IS NULL;')
    op.execute('UPDATE venue SET state = ' + "''" + ' WHERE state IS NULL;')

    op.alter_column('venue', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('venue', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('venue', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('venue', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('venue', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('venue', 'genres')
    op.drop_column('venue', 'seeking_description')
    op.drop_column('venue', 'website_link')
    op.drop_column('venue', 'looking')
    op.alter_column('artist', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('artist', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('artist', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('artist', 'seeking_description')
    op.drop_column('artist', 'looking')
    op.drop_column('artist', 'website_link')
    # ### end Alembic commands ###
